version: '3'

services:
  nodejs:
    build: .
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: lentera_network