version: '3'

services:
  nodejs:
    build: .
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - lentera_network

networks:
  lentera_network:
    external: true
